
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Sep 10 22:20:19 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREQUAL = 28;
  public static final int LBRACKET = 39;
  public static final int CHAR = 48;
  public static final int CONST = 6;
  public static final int GRLESSER = 30;
  public static final int LPAREN = 37;
  public static final int GREATER = 27;
  public static final int SEMI = 19;
  public static final int CONTINUE = 14;
  public static final int LESS = 29;
  public static final int MINUS = 21;
  public static final int RPAREN = 38;
  public static final int AND = 31;
  public static final int DOUBLEPLUS = 43;
  public static final int OR = 32;
  public static final int BOOL = 49;
  public static final int COMMA = 42;
  public static final int CLASS = 44;
  public static final int DIV = 23;
  public static final int PLUS = 20;
  public static final int IF = 9;
  public static final int DOT = 36;
  public static final int NOEQUAL = 26;
  public static final int FINDANY = 16;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int RBRACKET = 40;
  public static final int EQUAL = 34;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int DOUBLEMINUS = 33;
  public static final int MUL = 22;
  public static final int NUMBER = 47;
  public static final int MOD = 24;
  public static final int IDENT = 46;
  public static final int BREAK = 7;
  public static final int VOID = 5;
  public static final int FOREACH = 45;
  public static final int COLON = 35;
  public static final int LBRACE = 17;
  public static final int ELSE = 8;
  public static final int READ = 12;
  public static final int WHILE = 10;
  public static final int DOUBLEEQUAL = 25;
  public static final int RBRACE = 18;
  public static final int EXTENDS = 13;
  public static final int PROG = 2;
  public static final int FOLLOWS = 41;
  public static final int PRINT = 3;
  public static final int FINDANDREPLACE = 15;
}

