
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 20 01:48:18 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREQUAL = 31;
  public static final int MAP = 18;
  public static final int LBRACKET = 42;
  public static final int CONST = 9;
  public static final int CHAR = 4;
  public static final int GRLESSER = 33;
  public static final int LPAREN = 40;
  public static final int GREATER = 30;
  public static final int SEMI = 21;
  public static final int CONTINUE = 17;
  public static final int LESS = 32;
  public static final int MINUS = 24;
  public static final int RPAREN = 41;
  public static final int AND = 34;
  public static final int DOUBLEPLUS = 46;
  public static final int OR = 35;
  public static final int COMMA = 45;
  public static final int BOOL = 5;
  public static final int CLASS = 47;
  public static final int DIV = 26;
  public static final int PLUS = 23;
  public static final int IF = 12;
  public static final int DOT = 39;
  public static final int NOEQUAL = 29;
  public static final int EOF = 0;
  public static final int RETURN = 7;
  public static final int RBRACKET = 43;
  public static final int EQUAL = 37;
  public static final int DOUBLEMINUS = 36;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int MUL = 25;
  public static final int NUMBER = 3;
  public static final int MOD = 27;
  public static final int BREAK = 10;
  public static final int IDENT = 22;
  public static final int VOID = 8;
  public static final int COLON = 38;
  public static final int LBRACE = 19;
  public static final int ELSE = 11;
  public static final int READ = 15;
  public static final int WHILE = 13;
  public static final int DOUBLEEQUAL = 28;
  public static final int RBRACE = 20;
  public static final int EXTENDS = 16;
  public static final int PROG = 2;
  public static final int FOLLOWS = 44;
  public static final int PRINT = 6;
}

