
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 22 00:41:17 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREQUAL = 27;
  public static final int MAP = 15;
  public static final int LBRACKET = 38;
  public static final int CHAR = 46;
  public static final int CONST = 6;
  public static final int GRLESSER = 29;
  public static final int LPAREN = 36;
  public static final int GREATER = 26;
  public static final int SEMI = 18;
  public static final int CONTINUE = 14;
  public static final int LESS = 28;
  public static final int MINUS = 20;
  public static final int RPAREN = 37;
  public static final int AND = 30;
  public static final int DOUBLEPLUS = 42;
  public static final int OR = 31;
  public static final int BOOL = 47;
  public static final int COMMA = 41;
  public static final int CLASS = 43;
  public static final int DIV = 22;
  public static final int PLUS = 19;
  public static final int IF = 9;
  public static final int DOT = 35;
  public static final int NOEQUAL = 25;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int RBRACKET = 39;
  public static final int EQUAL = 33;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int DOUBLEMINUS = 32;
  public static final int MUL = 21;
  public static final int NUMBER = 45;
  public static final int MOD = 23;
  public static final int IDENT = 44;
  public static final int BREAK = 7;
  public static final int VOID = 5;
  public static final int COLON = 34;
  public static final int LBRACE = 16;
  public static final int ELSE = 8;
  public static final int READ = 12;
  public static final int WHILE = 10;
  public static final int DOUBLEEQUAL = 24;
  public static final int RBRACE = 17;
  public static final int EXTENDS = 13;
  public static final int PROG = 2;
  public static final int FOLLOWS = 40;
  public static final int PRINT = 3;
}

